* rsscript2-mode -- rescript mode with tree-sitter

Emacs 29 brings treesit, elgot and something interesting. This repo is an attempt to add treesit support for rescript-mode. Due to the existance of rescript-mode, I name this repo rescript2-mode.

- https://github.com/jjlee/rescript-mode
- https://github.com/reasonml-editor/reason-mode
- [[https://forum.rescript-lang.org/t/rescript-emacs-support-with-rescript-vscode/1056][Rescript emacs support with rescript-vscode]]

Tree-sitter related:

- https://github.com/nkrkv/tree-sitter-rescript
- https://github.com/lambdadog/rescript-tree-sitter-mode

Prereuquest treesit knowledge

- [[https://tree-sitter.github.io/tree-sitter/using-parsers][Using Parsers]]
- [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Parsing-Program-Source.html][Parsing Program Source -- Elisp maunal]]
- [[https://casouri.github.io/note/2023/tree-sitter-starter-guide/index.html][Tree-sitter starter guide]]
- [[https://casouri.github.io/note/2021/emacs-tree-sitter/index.html][RFC: Emacs tree-sitter integration]]

Prerequest elisp knowledge

- [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Modes.html][Major and Minor Modes]]

Emacs 29 has 20 buil-in tree-sitter major modes for C, C++, C#, Java, ... from which we can learn some basic usage. Just use =M-x apropos -ts-mode$= to view them.

** known problem

To use rescript's treesit parser in Emacs, we need:

- libtree-sitter.dll or libtree-sitter.so (from tree-sitter)
- treesit.c and treesit.h (emacs build-in)
- treesit.el (emacs build-in, user api)
- libtree-sitter-rescript (third-party package)

If any of them broke, then treesit-rescript cannot work properly in Emacs. Maybe the first three is robust enough. The code below causes Emacs fall into infinite loop and connot recover by C-g:

#+BEGIN_SRC elisp
  (treesit-parse-string "//" 'rescript)
#+END_SRC

If I want to make a robust rescript treesit mode, maybe I need to improve tree-sitter-rescript.
